// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eDefects.Api.Data;

#nullable disable

namespace eDefects.Api.Migrations
{
    [DbContext(typeof(EDefectsDbContext))]
    [Migration("20250731103705_Inital Migration")]
    partial class InitalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eDefects.Api.Models.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CM1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CM2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CM3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFound")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DefectComponentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefectLineID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FindSourceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FoundBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PUGroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PriorityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProdLineID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProdUnitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Defects");
                });
#pragma warning restore 612, 618
        }
    }
}
